blank_issues_enabled: false
contact_links:
  - name: Common Issues
    url: https://github.com/thoughtsunificator/instagram-dm-unsender?tab=readme-ov-file
    about: Check the README for common issues.
